spring.application.name=parallel

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:mariadb://localhost:3306/parallel_batch?rewriteBatchedStatements=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.batch.jdbc.initialize-schema=never

# CONFIGURAZIONE FILE E BATCH
batch.input.file.name=people-1000000.csv
batch.input.file.lines=1000000
batch.grid.size=12
batch.chunk.size=1000

# CONFIGURAZIONE THREAD POOL (Ottimizzato per i5-13500)
batch.pool.core-size=12
batch.pool.max-size=20
batch.pool.queue-capacity=50